### ISSUE TITLE
Add completeness report settings

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/monitor50x30#6]
## Add modules

- [x] #7
- [x] Clusters - quantifying
- [x] Clusters - identify for computers
- [x] Clusters - identify for survey managers
- [x] Workload by team
- [x] Save settings

## Add validations

- [x] #9
- [x] #10

**Comment by arthur-shaw** [comment]
Closed with several prior commit, the last being f296be8
